# Generated by Django 5.2.5 on 2026-02-14 13:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Groups.groupmember",
                    ),
                ),
            ],
            options={
                "ordering": ["amount", "timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BiddingRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("scheduled_time", models.DateTimeField()),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bidding_rounds",
                        to="Groups.group",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_rounds",
                        to="Groups.groupmember",
                    ),
                ),
                (
                    "winning_bid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="winning_rounds",
                        to="Bidding.bid",
                    ),
                ),
            ],
            options={
                "db_table": "BiddingRound",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.AddField(
            model_name="bid",
            name="bidding_round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="Bidding.biddinground",
            ),
        ),
        migrations.AddConstraint(
            model_name="biddinground",
            constraint=models.UniqueConstraint(
                fields=("group", "round_number"), name="unique_biding_round"
            ),
        ),
    ]
