# Generated by Django 5.2.5 on 2026-03-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0001_initial'),
        ('Groups', '0006_alter_group_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount', 'timestamp']},
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('bidding_round', 'amount'), name='unique_bid_per_round'),
        ),
    ]
