# Generated by Django 5.2.5 on 2025-09-13 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target amount for the group', max_digits=12)),
                ('size', models.PositiveIntegerField(help_text='Number of members in the group', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration', models.PositiveIntegerField(help_text='Duration of the group in periods (e.g., months)')),
                ('winner_selection_method', models.CharField(choices=[('random', 'Random'), ('round_robin', 'Round Robin'), ('bid', 'Bid')], default='random', help_text='Method for selecting the winner each period', max_length=50)),
                ('start_date', models.DateField(help_text='Start date of the group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_members',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='custom_groups', through='Groups.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user'], name='group_membe_user_id_88c209_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group'], name='group_membe_group_i_d2cebc_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_group_user'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['start_date'], name='groups_start_d_56fe44_idx'),
        ),
    ]
