# Generated by Django 5.2.5 on 2025-09-14 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='role',
            field=models.CharField(default='member', max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='size',
            field=models.PositiveIntegerField(help_text='Number of members in the group', validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
