# Generated by Django 5.2.5 on 2025-10-31 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Groups", "0002_groupmember_role_alter_group_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="size",
            field=models.PositiveIntegerField(
                help_text="Number of members in the group",
                validators=[django.core.validators.MinValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="start_date",
            field=models.DateTimeField(help_text="Start date of the group"),
        ),
        migrations.AlterField(
            model_name="group",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Target amount for the group",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="winner_selection_method",
            field=models.CharField(
                choices=[
                    ("random", "Random"),
                    ("round_robin", "Round Robin"),
                    ("bid", "Bid"),
                ],
                default="random",
                help_text="Method for selecting the winner each month.",
                max_length=50,
            ),
        ),
    ]
