# Generated by Django 5.2.5 on 2026-01-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Groups", "0003_alter_group_size_alter_group_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="has_won",
            field=models.BooleanField(default=False),
        ),
    ]
