# Generated by Django 5.2.5 on 2026-02-14 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Groups", "0004_groupmember_has_won"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="target_amount",
            field=models.PositiveIntegerField(
                help_text="Target amount for the group",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
