# Generated by Django 5.2.5 on 2026-03-29 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Groups", "0005_alter_group_target_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                through="Groups.GroupMember", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
